#!/bin/sh
exec 1>&2
exec < /dev/tty
CONSOLE_REGEXP='^\+((?!\/\/).)*console\.log\('
FILES=` git status --porcelain | grep -e '^[AM]\(.*\)$' | cut -c 3- | tr '\n' ' '`
ERROR_FOUND=0
for FILE in $FILES; do
  DIFF_IN_ERROR=$(git diff -U0 --cached $FILE | grep -P $CONSOLE_REGEXP)
  if test $(echo $DIFF_IN_ERROR | wc -l) != 0; then
    if [ $ERROR_FOUND -eq 0 ]; then
      ERROR_FOUND=1
      echo "There are some occurrences of console.log at your modification"
    fi
    echo "---------------------------"
    echo "|" $FILE
    echo "---------------------------"
    echo "|" $DIFF_IN_ERROR
    echo "---------------------------"
  fi
done
if [ $ERROR_FOUND -eq 1 ]; then
  read -p "Are you sure want to continue? (y/n) " yn
  echo $yn | grep ^[Yy]$ > /dev/null
  if [ $? -eq 0 ]
  then
    exit 0;
  else
    exit 1;
  fi
fi
exit 0
