#!/bin/bash
unset $(git rev-parse --local-env-vars)
exec 1>&2
exec < /dev/tty
PATTERN_EXCLUSION='\d:\+((?!\/\/).)*(console\.log|dump)\s*\('
diff-lines() {
    local path=
    local line=
    while read; do
        esc=$'\033'
        if [[ $REPLY =~ ---\ (a/)?.* ]]; then
            continue
        elif [[ $REPLY =~ \+\+\+\ (b/)?([^[:blank:]$esc]+).* ]]; then
            path=${BASH_REMATCH[2]}
        elif [[ $REPLY =~ @@\ -[0-9]+(,[0-9]+)?\ \+([0-9]+)(,[0-9]+)?\ @@.* ]]; then
            line=${BASH_REMATCH[2]}
        elif [[ $REPLY =~ ^($esc\[[0-9;]+m)*([\ +-]) ]]; then
            echo "$path:$line:$REPLY"
            if [[ ${BASH_REMATCH[2]} != - ]]; then
                ((line++))
            fi
        fi
    done
}
FILES=$(git diff --cached --name-only --relative --diff-filter=AMRC "*.ts" "*.js" "*.vue" "*.php" | sed 's| |\\ |g')
ERROR_FOUND=0
for FILE in $FILES; do
  DIFF_IN_ERROR=$(git diff -U0 --cached $FILE | diff-lines | grep -P "$PATTERN_EXCLUSION")
  if [[ ! -z "$DIFF_IN_ERROR" ]]; then
    if [ $ERROR_FOUND -eq 0 ]; then
      ERROR_FOUND=1
      echo "You forgot some pattern that should'nt be commited"
    fi
    echo -e "$DIFF_IN_ERROR"
  fi
done

if [ $ERROR_FOUND -eq 1 ]; then
  read -p "Are you sure want to continue? (y/n) " yn
  echo $yn | grep ^[Yy]$ > /dev/null
  if [ $? -eq 0 ]
  then
    exit 0;
  else
    exit 1;
  fi
fi
exit 0
